export const ImageSources = {
    StartUpBg:require("../../assets/stockphoto/register_bg.jpg"),
    LandingBg:require("../../assets/stockphoto/landing_bg.jpg"),
    Menu: require("../../assets/menu.png"),
    Close: require("../../assets/close-button.png"),
    Add: require("../../assets/add.png"),
    LeftArrow: require("../../assets/left-arrow.png"),
    DownArrow: require("../../assets/down-arrow.png"),
    GPay: require("../../assets/gpay.png"),
    Paypal: require("../../assets/paypal.png"),
    shippingCart: require("../../assets/shipping.png"),
    DemoProfilePic: require("../../assets/profile.jpg"),
    TutorialImage001: require("../../assets/stockphoto/tutoiral001.jpg"),
    TutorialImage002: require("../../assets/stockphoto/tutoiral002.jpg"),
    TutorialImage003: require("../../assets/stockphoto/tutoiral003.jpg"),
    ReturnAndRefundImage: require("../../assets/returnAndRefund.png"),
    PaymentImage: require("../../assets/payment.png"),
    ProductImage001: require("../../assets/stockphoto/products/products001.png"),
    ProductImage002: require("../../assets/stockphoto/products/products002.png"),
    ProductImage003: require("../../assets/stockphoto/products/products003.png"),
    ProductImage004: require("../../assets/stockphoto/products/products004.png"),
    ProductImage005: require("../../assets/stockphoto/products/products005.png"),
    PromotionImage001: require("../../assets/stockphoto/promotion/001.jpg"),
    PromotionImage002: require("../../assets/stockphoto/promotion/002.jpg"),
    PromotionImage003: require("../../assets/stockphoto/promotion/003.jpg"),
    PromotionImage004: require("../../assets/stockphoto/promotion/004.jpg"),
    PromotionImage005: require("../../assets/stockphoto/promotion/005.jpg"),
    PromotionImage006: require("../../assets/stockphoto/promotion/006.jpg"),
    ProductDetailShot01: require("../../assets/stockphoto/product_detail/product_shot_01.png"),
    ProductDetailShot02: require("../../assets/stockphoto/product_detail/product_shot_02.png"),
    ProductDetailShot03: require("../../assets/stockphoto/product_detail/product_shot_03.png"),
    ProductDetailShot04: require("../../assets/stockphoto/product_detail/product_shot_04.png"),
    ProductDetailShot05: require("../../assets/stockphoto/product_detail/product_shot_05.png"),
    DHL: require("../../assets/dhl.png"),
    UBS: require("../../assets/ubs.png"),
    FEDDEX: require("../../assets/fedex.png"),
}
