export const ScreenNames = {
    ShoppingCart:'ShoppingCart',
    root: 'root',
    Startup: 'Startup',
    Landing: 'Landing',
    Login: 'Login',
    AppMain: 'AppMain',
    InternalBrowser: 'InternalBrowser',
    TutorialScreen: 'TutorialScreen',
    AppMain: 'AppMain',
    Home: 'Home',
    MyProfileView: 'MyProfileView',
    Settings: 'Settings',
    Help: 'Help',
    RegisterScreen:'RegisterScreen',
    LoginScreen:'LoginScreen',
    //Login
    ExploreShop:'ExploreShop',
    FindProduct:'FindProduct',
    ClothesListing:'ClothesListing',
    CheckoutScreen:'CheckoutScreen',
    ClothesDetail:'ClothesDetail',
    InboxMessage:'InboxMessage',
    InboxDetail:'InboxDetail', 
}